### ISSUE TITLE
Upgrade README.md to include how to build and run by command line

### ISSUE THREAD

**Issue by jabrena** [jaapcoomans/spring-boot-modules#1]
Hi,

I watched your video in `Oracle Code One`, but I missed in the `README.md` the instructions to build and run the project by command line. In the video you used IntelliJ and not the terminal.

Can you upgrade the repo, please?

Many thanks in advance

Juan Antonio

**Comment by jaapcoomans** [comment]
Hey Juan Antonio, 

Thanks for the feedback! 
I'll add a little section on building and running to the README. Great suggestion.

What you can do to build and run is to first run `mvn package`. After that you can either build the Docker container separately (`docker build .`), or use the docker-compose file in the `local` folder.

**Comment by jaapcoomans** [comment]
Hi @jabrena,

I added [a section on building and running here](https://github.com/jaapcoomans/spring-boot-modules#building-and-running-the-application).
Is this what you meant?

Cheers,
Jaap

**Comment by jabrena** [comment]
Yes @jaapcoomans,

many thanks
